### ISSUE TITLE
Student feedback

### ISSUE THREAD

**Issue by Hadrien-lcrx** [datacamp/courses-intro-to-sql#114]
"Hi I have been completing your courses as part of my uni course to learn sql and coding with Jupyter notebook. I was given an assignment using csv and sqlite data files and I had to create a data visualization. Thebfirst data set was NSW crime at the following link: https://data.nsw.gov.au/data/dataset/c18d2459-47c7-46b8-b9db-91d9365b1850 and the second was soccer statistics from the Barcelona Olympics. The problem I faced was that there is no tutorial or any product that shows how to create a graph from start to finish. Are you able to create an example with my dataset explaining the step by step process from start to finish. Then with an sqlite file, then comparing the two files. Your tutorials are great, but lack a complete example with this type of data. The Tips data is too basic and in a format that is easy to use. Plus there is no examples showing how to graph an sqlite file that has multiple tabs. Your help would be greatly appreciated. Regards Bradley Halicek bradley.s.halicek@student.uts.edu.au"

Cf bradley.s.halicek@student.uts.edu.au #50568

**Comment by ncarchedi** [comment]
I'll discuss this with Anthony later today, but this sort of thing is not appropriate for a github issue. It's essentially a consulting request and it won't scale. Please ask this person to join our community slack organization and post the question there. cc @bakera81

**Comment by bakera81** [comment]
@ncarchedi I have already spoken with Hadrien about this.
