### ISSUE TITLE
Link to Joining Data in PostgreSQL to close course

### ISSUE THREAD

**Issue by ismayc** [datacamp/courses-intro-to-sql#117]
Might be a great way to get non-subscribers to subscribe and take the follow-up course. Suggested via community slack in DataCamp USA

<img width="431" alt="screenshot 2018-01-20 13 43 19" src="https://user-images.githubusercontent.com/9215614/35188321-f5d551fa-fde7-11e7-870e-e4b9f882bd94.png">

**Comment by yashasroy** [comment]
@ismayc Good idea. Somewhere on the product roadmap is a plan to "recommend" the next course Netflix style, but in the meanwhile, I think a link in the assignment text or success message of the final exercise would be great. I'll get to this next week (but feel free to issue a PR yourself as well, if you want to)
