### ISSUE TITLE
Script is down in Multiple Choice Questions | Chapter 1 Exercise 3

### ISSUE THREAD

**Issue by Hadrien-lcrx** [datacamp/courses-intro-to-sql#119]
On [Onboarding | Query Result](https://campus.datacamp.com/courses/intro-to-sql-for-data-science/selecting-columns?ex=3), the students are asked to execute a pre-defined query but the query doesn't appear. There's a similar issue on [Learning to COUNT](https://campus.datacamp.com/courses/intro-to-sql-for-data-science/selecting-columns?ex=10) and [HAVING a great time](https://campus.datacamp.com/courses/intro-to-sql-for-data-science/sorting-grouping-and-joins?ex=9).

Several students reached out about this issue previously referencing this first quiz, so seeing the result could be obtained by clicking on the table and checking the second row, I didn't realize this was **a general issue with the script on Multiple Choice Questions exercises**.

### Suggestions
Update the code to make the query appear. The query should apparently be
```sql
SELECT name
FROM people
```
and it [appears in the sample code of the .md file](https://github.com/datacamp/courses-intro-to-sql/blob/master/chapter1.md#onboarding--query-result), so the root of the issue seems to be elsewhere.

#### Onboarding
![image](https://user-images.githubusercontent.com/22552805/36349529-631bf2b6-1489-11e8-8434-a1fa672bc810.png)

#### Learning to COUNT
![image](https://user-images.githubusercontent.com/22552805/36349558-31b72c9e-148a-11e8-8e94-77da5a2b42b4.png)

#### HAVING a great time
![image](https://user-images.githubusercontent.com/22552805/36349563-60a798f4-148a-11e8-9235-9230b0824cfa.png)

Cf ibrahimmyriam7@gmail.com, #90784
Cc @bakera81 @Robert-cabral

**Comment by Hadrien-lcrx** [comment]
Another student reached out about this issue: crnelson10@gmail.com, #91090
Cc @bakera81 @Robert-cabral

**Comment by Hadrien-lcrx** [comment]
Another student reached out about this issue: timothypark@berkeley.edu, #90620
Cc @bakera81 @Robert-cabral

**Comment by Hadrien-lcrx** [comment]
Another student reached out about this issue: malcolm.clement@gmail.com, #91769
Cc @bakera81 @Robert-cabral

**Comment by yashasroy** [comment]
@Hadrien-lcrx I'm able to see the query in the exercises you listed:

<img width="1426" alt="screenshot 2018-02-22 10 09 57" src="https://user-images.githubusercontent.com/20912644/36546124-918472ae-17b8-11e8-8183-5e0296f8f390.png">

Can you confirm this is now the case for you as well? Seems to have been a learn bug.

**Comment by Hadrien-lcrx** [comment]
@yashasroy Yes it's working now! I'm closing. Thank you!

**Comment by LankyLou** [comment]
@yashasroy @Hadrien-lcrx Just to confirm there was a bug in campus that meant the query panel wasn't showing for multiple choice exercises in SQL that I fixed yesterday. This should now be totally resolved
