### ISSUE TITLE
Sample code is confusing in tabexercises

### ISSUE THREAD

**Issue by filipsch** [datacamp/courses-intro-to-sql#127]
Go to [this exercise](https://campus.datacamp.com/courses/intro-to-sql-for-data-science/aggregate-functions?ex=6). The sample code repeats the instructions of the _first_ tab in the comment, but when you write your SQL code under that comment and you solve the exercise, your code is kept and serves as the starting point for the next part. Now, you're asked to do something totally different, but there's still the SQL comment from the first tab. This can be very confusing for students, I think.

Suggestion: just get rid of sample code in TabExercises alltogether.

**Comment by klmedeiros** [comment]
I flagged in my brain this when I took the course a few weekends ago but haven't gotten to fixing it yet, so thanks for raising the issue, @filipsch. I think it's probably our responsibility, but @richierocks should weigh in.

**Comment by richierocks** [comment]
The logic of how code appears in multi-step exercises in resolved now.
